export interface VerifiedSnapshot {
  factualData: any;
}

export const VERIFIED_SNAPSHOTS: Record<string, any> = {
  shadcn: {
    profile: {
      username: 'shadcn',
      name: 'shadcn',
      avatar_url: 'https://avatars.githubusercontent.com/u/124599?v=4',
      html_url: 'https://github.com/shadcn',
      bio: 'Design systems, UI components, and web applications.',
      company: '@vercel',
      location: 'San Francisco, CA',
      blog_url: 'https://ui.shadcn.com',
      twitter_username: 'shadcn',
      public_repos_count: 52,
      public_gists_count: 4,
      followers_count: 124000,
      following_count: 32,
      created_at: '2009-09-08T18:24:12Z',
      updated_at: '2026-03-28T14:10:00Z',
      accountAgeYears: 16.5,
    },
    stats: {
      totalStars: 98400,
      totalForks: 8900,
      totalOpenIssues: 245,
      reposInspectedCount: 4,
      originalReposCount: 42,
      forkedReposCount: 10,
      reposWithDescription: 48,
      reposWithLicense: 50,
      topLanguages: [
        { language: 'TypeScript', count: 34 },
        { language: 'JavaScript', count: 10 },
        { language: 'CSS', count: 4 },
        { language: 'MDX', count: 2 },
      ],
    },
    repositoriesSummary: [
      {
        name: 'ui',
        description: 'Beautifully designed components that you can copy and paste into your apps. Accessible. Customizable. Open Source.',
        fork: false,
        stars: 78500,
        forks: 6400,
        language: 'TypeScript',
        topics: ['design-system', 'react', 'tailwind', 'radix-ui', 'components'],
        pushed_at: '2026-03-27T19:22:10Z',
        created_at: '2023-01-18T16:14:00Z',
        hasLicense: true,
      },
      {
        name: 'taxonomy',
        description: 'An open source application built using the new Router, Server Components and everything new in Next.js 13.',
        fork: false,
        stars: 18200,
        forks: 2300,
        language: 'TypeScript',
        topics: ['nextjs', 'react-server-components', 'tailwind', 'prisma'],
        pushed_at: '2025-11-12T08:10:00Z',
        created_at: '2022-10-25T14:22:00Z',
        hasLicense: true,
      },
      {
        name: 'next-template',
        description: 'Next.js 14 template with Tailwind CSS, Radix UI, TypeScript and Lucide icons.',
        fork: false,
        stars: 3200,
        forks: 410,
        language: 'TypeScript',
        topics: ['template', 'starter', 'nextjs', 'tailwind'],
        pushed_at: '2025-08-10T11:45:00Z',
        created_at: '2023-03-01T10:00:00Z',
        hasLicense: true,
      },
      {
        name: 'typography',
        description: 'A typographic system built with Tailwind CSS and CSS variables.',
        fork: false,
        stars: 1100,
        forks: 115,
        language: 'CSS',
        topics: ['typography', 'tailwind', 'design'],
        pushed_at: '2024-05-18T12:00:00Z',
        created_at: '2023-05-10T14:00:00Z',
        hasLicense: true,
      },
    ],
    deepInspectedRepos: [
      {
        id: 5901234,
        name: 'ui',
        full_name: 'shadcn/ui',
        html_url: 'https://github.com/shadcn/ui',
        description: 'Beautifully designed components that you can copy and paste into your apps. Accessible. Customizable. Open Source.',
        fork: false,
        stargazers_count: 78500,
        forks_count: 6400,
        open_issues_count: 180,
        language: 'TypeScript',
        topics: ['design-system', 'react', 'tailwind', 'radix-ui', 'components'],
        created_at: '2023-01-18T16:14:00Z',
        updated_at: '2026-03-27T19:22:10Z',
        pushed_at: '2026-03-27T19:22:10Z',
        default_branch: 'main',
        size_kb: 48200,
        hasReadme: true,
        readmeLength: 4890,
        readmeSnippet: '# shadcn/ui\n\nBeautifully designed components that you can copy and paste into your apps. Accessible. Customizable. Open Source.\n\n## Documentation\n\nVisit [ui.shadcn.com](https://ui.shadcn.com) for full documentation and guides.\n\n## CLI Installation\n\nRun the init command to create a new project:\n```bash\nnpx shadcn@latest init\n```',
        hasLicense: true,
        licenseName: 'MIT License',
        hasGitignore: true,
        hasWorkflows: true,
        workflowFiles: ['ci.yml', 'release.yml', 'e2e.yml'],
        hasTests: true,
        testSignalsFound: ['vitest.config.ts', '__tests__', 'cli.test.ts'],
        dependencyFiles: ['package.json', 'pnpm-workspace.yaml'],
        packageScripts: {
          build: 'turbo run build',
          test: 'vitest run',
          lint: 'eslint . --ext .ts,.tsx',
          format: 'prettier --write "**/*.{ts,tsx,md}"',
        },
        dependenciesCount: 18,
        devDependenciesCount: 24,
      },
      {
        id: 5612345,
        name: 'taxonomy',
        full_name: 'shadcn/taxonomy',
        html_url: 'https://github.com/shadcn/taxonomy',
        description: 'An open source application built using the new Router, Server Components and everything new in Next.js 13.',
        fork: false,
        stargazers_count: 18200,
        forks_count: 2300,
        open_issues_count: 42,
        language: 'TypeScript',
        topics: ['nextjs', 'react-server-components', 'tailwind', 'prisma'],
        created_at: '2022-10-25T14:22:00Z',
        updated_at: '2025-11-12T08:10:00Z',
        pushed_at: '2025-11-12T08:10:00Z',
        default_branch: 'main',
        size_kb: 14200,
        hasReadme: true,
        readmeLength: 3400,
        readmeSnippet: '# Taxonomy\n\nAn open source application built using Next.js App Router, Server Components, React 18, Tailwind CSS, Prisma and Stripe.\n\n## Features\n- App Router\n- Authentication with NextAuth.js\n- Subscriptions with Stripe\n- ORM using Prisma',
        hasLicense: true,
        licenseName: 'MIT License',
        hasGitignore: true,
        hasWorkflows: true,
        workflowFiles: ['test.yml', 'deploy.yml'],
        hasTests: true,
        testSignalsFound: ['jest.config.js', 'e2e.spec.ts'],
        dependencyFiles: ['package.json'],
        packageScripts: {
          dev: 'next dev',
          build: 'next build',
          test: 'jest --passWithNoTests',
          lint: 'next lint',
        },
        dependenciesCount: 22,
        devDependenciesCount: 15,
      },
    ],
  },

  torvalds: {
    profile: {
      username: 'torvalds',
      name: 'Linus Torvalds',
      avatar_url: 'https://avatars.githubusercontent.com/u/1024025?v=4',
      html_url: 'https://github.com/torvalds',
      bio: 'Creator of Linux and Git.',
      company: 'Linux Foundation',
      location: 'Portland, OR',
      blog_url: 'https://kernel.org',
      twitter_username: null,
      public_repos_count: 7,
      public_gists_count: 0,
      followers_count: 215000,
      following_count: 0,
      created_at: '2011-09-03T15:26:22Z',
      updated_at: '2026-03-25T10:11:00Z',
      accountAgeYears: 14.5,
    },
    stats: {
      totalStars: 198000,
      totalForks: 54000,
      totalOpenIssues: 380,
      reposInspectedCount: 4,
      originalReposCount: 6,
      forkedReposCount: 1,
      reposWithDescription: 6,
      reposWithLicense: 5,
      topLanguages: [
        { language: 'C', count: 5 },
        { language: 'Makefile', count: 1 },
      ],
    },
    repositoriesSummary: [
      {
        name: 'linux',
        description: 'Linux kernel source tree',
        fork: false,
        stars: 185000,
        forks: 52000,
        language: 'C',
        topics: ['kernel', 'linux', 'operating-system', 'c'],
        pushed_at: '2026-03-28T02:15:00Z',
        created_at: '2011-09-04T22:48:00Z',
        hasLicense: true,
      },
      {
        name: 'uemacs',
        description: 'MicroEMACS editor',
        fork: false,
        stars: 1400,
        forks: 260,
        language: 'C',
        topics: ['editor', 'emacs', 'c'],
        pushed_at: '2024-01-15T18:22:00Z',
        created_at: '2014-06-01T12:00:00Z',
        hasLicense: true,
      },
      {
        name: 'subsurface-for-dirk',
        description: 'Subsurface dive log application',
        fork: false,
        stars: 1200,
        forks: 210,
        language: 'C',
        topics: ['dive-log', 'subsurface'],
        pushed_at: '2023-11-20T10:00:00Z',
        created_at: '2011-10-10T14:00:00Z',
        hasLicense: true,
      },
    ],
    deepInspectedRepos: [
      {
        id: 2325298,
        name: 'linux',
        full_name: 'torvalds/linux',
        html_url: 'https://github.com/torvalds/linux',
        description: 'Linux kernel source tree',
        fork: false,
        stargazers_count: 185000,
        forks_count: 52000,
        open_issues_count: 350,
        language: 'C',
        topics: ['kernel', 'linux', 'operating-system', 'c'],
        created_at: '2011-09-04T22:48:00Z',
        updated_at: '2026-03-28T02:15:00Z',
        pushed_at: '2026-03-28T02:15:00Z',
        default_branch: 'master',
        size_kb: 4850000,
        hasReadme: true,
        readmeLength: 3200,
        readmeSnippet: '# Linux kernel\n\nLinux is a clone of the operating system Unix, written from scratch by Linus Torvalds with assistance from a loosely-knit team of hackers across the Net.\n\nIt has all the features you would expect in a modern fully-fledged Unix, including true multitasking, virtual memory, shared libraries, proper memory management, and TCP/IP networking.',
        hasLicense: true,
        licenseName: 'GPL-2.0 License',
        hasGitignore: true,
        hasWorkflows: false,
        workflowFiles: [],
        hasTests: true,
        testSignalsFound: ['tools/testing', 'kselftest'],
        dependencyFiles: ['Makefile', 'Kconfig'],
        packageScripts: null,
        dependenciesCount: 0,
        devDependenciesCount: 0,
      },
    ],
  },

  gaearon: {
    profile: {
      username: 'gaearon',
      name: 'Dan Abramov',
      avatar_url: 'https://avatars.githubusercontent.com/u/810438?v=4',
      html_url: 'https://github.com/gaearon',
      bio: 'Working on Bluesky. Co-author of Redux and Create React App.',
      company: '@bluesky-social',
      location: 'London, UK',
      blog_url: 'https://overreacted.io',
      twitter_username: 'dan_abramov',
      public_repos_count: 260,
      public_gists_count: 78,
      followers_count: 89000,
      following_count: 172,
      created_at: '2011-05-25T18:18:31Z',
      updated_at: '2026-03-20T11:40:00Z',
      accountAgeYears: 14.8,
    },
    stats: {
      totalStars: 112000,
      totalForks: 14500,
      totalOpenIssues: 120,
      reposInspectedCount: 4,
      originalReposCount: 190,
      forkedReposCount: 70,
      reposWithDescription: 180,
      reposWithLicense: 195,
      topLanguages: [
        { language: 'JavaScript', count: 120 },
        { language: 'TypeScript', count: 85 },
        { language: 'HTML', count: 15 },
      ],
    },
    repositoriesSummary: [
      {
        name: 'redux',
        description: 'Predictable state container for JavaScript apps',
        fork: false,
        stars: 60500,
        forks: 15300,
        language: 'TypeScript',
        topics: ['state-management', 'redux', 'javascript', 'react'],
        pushed_at: '2025-10-11T12:00:00Z',
        created_at: '2015-05-30T00:00:00Z',
        hasLicense: true,
      },
      {
        name: 'overreacted.io',
        description: 'Personal blog about software development, React, and mental models.',
        fork: false,
        stars: 6200,
        forks: 890,
        language: 'JavaScript',
        topics: ['blog', 'react', 'gatsby'],
        pushed_at: '2025-06-14T09:15:00Z',
        created_at: '2018-11-20T10:00:00Z',
        hasLicense: true,
      },
    ],
    deepInspectedRepos: [
      {
        id: 36535520,
        name: 'redux',
        full_name: 'reduxjs/redux',
        html_url: 'https://github.com/reduxjs/redux',
        description: 'Predictable state container for JavaScript apps',
        fork: false,
        stargazers_count: 60500,
        forks_count: 15300,
        open_issues_count: 30,
        language: 'TypeScript',
        topics: ['state-management', 'redux', 'javascript'],
        created_at: '2015-05-30T00:00:00Z',
        updated_at: '2025-10-11T12:00:00Z',
        pushed_at: '2025-10-11T12:00:00Z',
        default_branch: 'master',
        size_kb: 18200,
        hasReadme: true,
        readmeLength: 5400,
        readmeSnippet: '# Redux\n\nRedux is a predictable state container for JavaScript apps.\n\nIt helps you write applications that behave consistently, run in different environments (client, server, and native), and are easy to test.',
        hasLicense: true,
        licenseName: 'MIT License',
        hasGitignore: true,
        hasWorkflows: true,
        workflowFiles: ['test.yml', 'release.yml'],
        hasTests: true,
        testSignalsFound: ['vitest.config.ts', 'test'],
        dependencyFiles: ['package.json'],
        packageScripts: {
          test: 'vitest run',
          build: 'tsup',
          lint: 'eslint .',
        },
        dependenciesCount: 5,
        devDependenciesCount: 16,
      },
    ],
  },

  sindresorhus: {
    profile: {
      username: 'sindresorhus',
      name: 'Sindre Sorhus',
      avatar_url: 'https://avatars.githubusercontent.com/u/170270?v=4',
      html_url: 'https://github.com/sindresorhus',
      bio: 'Full-time open-sourcerer. Creator of 1,000+ npm packages and macOS apps.',
      company: 'Self-employed',
      location: 'Thailand',
      blog_url: 'https://sindresorhus.com',
      twitter_username: 'sindresorhus',
      public_repos_count: 1100,
      public_gists_count: 90,
      followers_count: 62000,
      following_count: 30,
      created_at: '2009-12-20T22:57:00Z',
      updated_at: '2026-03-27T08:00:00Z',
      accountAgeYears: 16.3,
    },
    stats: {
      totalStars: 340000,
      totalForks: 28000,
      totalOpenIssues: 140,
      reposInspectedCount: 4,
      originalReposCount: 1050,
      forkedReposCount: 50,
      reposWithDescription: 1020,
      reposWithLicense: 1080,
      topLanguages: [
        { language: 'JavaScript', count: 620 },
        { language: 'TypeScript', count: 320 },
        { language: 'Swift', count: 110 },
      ],
    },
    repositoriesSummary: [
      {
        name: 'awesome',
        description: 'Awesome lists about all kinds of interesting topics',
        fork: false,
        stars: 342000,
        forks: 28000,
        language: 'Markdown',
        topics: ['awesome', 'awesome-list', 'resources'],
        pushed_at: '2026-03-27T10:00:00Z',
        created_at: '2014-07-11T13:00:00Z',
        hasLicense: true,
      },
      {
        name: 'ky',
        description: 'Tiny & elegant HTTP client based on window.fetch',
        fork: false,
        stars: 14200,
        forks: 480,
        language: 'TypeScript',
        topics: ['fetch', 'http', 'client', 'promise'],
        pushed_at: '2026-02-14T09:00:00Z',
        created_at: '2018-09-08T15:00:00Z',
        hasLicense: true,
      },
    ],
    deepInspectedRepos: [
      {
        id: 147983713,
        name: 'ky',
        full_name: 'sindresorhus/ky',
        html_url: 'https://github.com/sindresorhus/ky',
        description: 'Tiny & elegant HTTP client based on window.fetch',
        fork: false,
        stargazers_count: 14200,
        forks_count: 480,
        open_issues_count: 18,
        language: 'TypeScript',
        topics: ['fetch', 'http', 'client', 'promise'],
        created_at: '2018-09-08T15:00:00Z',
        updated_at: '2026-02-14T09:00:00Z',
        pushed_at: '2026-02-14T09:00:00Z',
        default_branch: 'main',
        size_kb: 1200,
        hasReadme: true,
        readmeLength: 6800,
        readmeSnippet: '# ky\n\n> Tiny & elegant HTTP client based on window.fetch\n\nKy targets modern browsers, Node.js, and Deno. It has a tiny footprint and clean Promise-based API.',
        hasLicense: true,
        licenseName: 'MIT License',
        hasGitignore: true,
        hasWorkflows: true,
        workflowFiles: ['main.yml'],
        hasTests: true,
        testSignalsFound: ['ava.config.js', 'test.js'],
        dependencyFiles: ['package.json'],
        packageScripts: {
          test: 'xo && ava && tsd',
        },
        dependenciesCount: 0,
        devDependenciesCount: 8,
      },
    ],
  },

  octocat: {
    profile: {
      username: 'octocat',
      name: 'The Octocat',
      avatar_url: 'https://avatars.githubusercontent.com/u/583231?v=4',
      html_url: 'https://github.com/octocat',
      bio: 'Official mascot and representative for GitHub.',
      company: '@github',
      location: 'San Francisco',
      blog_url: 'https://github.blog',
      twitter_username: 'github',
      public_repos_count: 8,
      public_gists_count: 8,
      followers_count: 15400,
      following_count: 9,
      created_at: '2011-01-25T18:44:36Z',
      updated_at: '2026-03-12T10:14:22Z',
      accountAgeYears: 15.2,
    },
    stats: {
      totalStars: 4200,
      totalForks: 3200,
      totalOpenIssues: 18,
      reposInspectedCount: 3,
      originalReposCount: 6,
      forkedReposCount: 2,
      reposWithDescription: 7,
      reposWithLicense: 5,
      topLanguages: [
        { language: 'Ruby', count: 3 },
        { language: 'HTML', count: 2 },
        { language: 'CSS', count: 1 },
      ],
    },
    repositoriesSummary: [
      {
        name: 'Hello-World',
        description: 'My first repository on GitHub!',
        fork: false,
        stars: 2600,
        forks: 2400,
        language: 'HTML',
        topics: ['sample', 'hello-world'],
        pushed_at: '2025-05-10T12:00:00Z',
        created_at: '2011-01-26T19:01:00Z',
        hasLicense: true,
      },
      {
        name: 'Spoon-Knife',
        description: 'This repo is for forking around.',
        fork: false,
        stars: 1200,
        forks: 600,
        language: 'HTML',
        topics: ['git-workflow', 'forking'],
        pushed_at: '2024-08-11T10:00:00Z',
        created_at: '2011-01-27T19:30:00Z',
        hasLicense: false,
      },
    ],
    deepInspectedRepos: [
      {
        id: 1296269,
        name: 'Hello-World',
        full_name: 'octocat/Hello-World',
        html_url: 'https://github.com/octocat/Hello-World',
        description: 'My first repository on GitHub!',
        fork: false,
        stargazers_count: 2600,
        forks_count: 2400,
        open_issues_count: 12,
        language: 'HTML',
        topics: ['sample', 'hello-world'],
        created_at: '2011-01-26T19:01:00Z',
        updated_at: '2025-05-10T12:00:00Z',
        pushed_at: '2025-05-10T12:00:00Z',
        default_branch: 'master',
        size_kb: 120,
        hasReadme: true,
        readmeLength: 120,
        readmeSnippet: '# Hello World!\n\nThis is the Octocat\'s first GitHub repository.',
        hasLicense: true,
        licenseName: 'MIT License',
        hasGitignore: false,
        hasWorkflows: false,
        workflowFiles: [],
        hasTests: false,
        testSignalsFound: [],
        dependencyFiles: [],
        packageScripts: null,
        dependenciesCount: 0,
        devDependenciesCount: 0,
      },
    ],
  },
};
